    function safeExternalUrl(value) { try { const url = new URL(String(value || '')); return url.protocol === 'https:' && !url.username && !url.password ? url.href : ''; } catch (_) { return ''; } }
    function stableNewsId(url) { let hash = 2166136261; for (const character of url) { hash ^= character.charCodeAt(0); hash = Math.imul(hash,16777619); } return `news_${(hash >>> 0).toString(36)}`; }
    function plainNewsText(value) { return String(value || '').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/[ \t]+/g,' ').trim(); }
    function normalizeNewsItem(item) {
        const url = safeExternalUrl(item.url || item.link); const title = String(item.title || '').trim().slice(0,220);
        if (!url || !title) return null;
        const source = String(item.host || item.domain || item.source || new URL(url).hostname).trim().slice(0,80);
        const dateText = String(item.seendate || item.published_at || item.publishedAt || '').trim();
        const parsed = /^\d{14}$/.test(dateText) ? Date.parse(`${dateText.slice(0,4)}-${dateText.slice(4,6)}-${dateText.slice(6,8)}T${dateText.slice(8,10)}:${dateText.slice(10,12)}:${dateText.slice(12,14)}Z`) : Date.parse(dateText);
        return { id: stableNewsId(url), title, url, source, description: plainNewsText(item.description || item.summary).slice(0,700), content: plainNewsText(item.text || item.content).slice(0,900), imageUrl: safeExternalUrl(item.image || item.socialimage || item.og || ''), publishedAt: Number.isFinite(parsed) ? parsed : now(), fetchedAt: now(), provider: String(item.provider || 'GDELT').slice(0,40) };
    }
    async function fetchNewsJson(url) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(),15000); try { const response = await fetch(url,{ signal: controller.signal, headers: { Accept:'application/json' } }); if (!response.ok) throw new Error(`资讯源暂不可用（HTTP ${response.status}）。`); return await response.json(); } finally { clearTimeout(timer); } }
    async function fetchRealNews(force = false) {
        if (newsBusy) return;
        const world = loadState(); if (!force && world.newsItems.length && now() - world.newsFetchedAt < 6 * 3600000) return;
        if (force && now() - world.newsFetchedAt < 30000) { showToast('请稍后再刷新真实资讯。'); return; }
        newsBusy = true; render();
        let source = 'FreeNews'; let rows = []; let outcome = '';
        try {
            try { const payload = await fetchNewsJson('https://freenewsapi.ai/v1/search?date=24h&lang=en&size=18&sort=date'); rows = safeList(payload.results).map(item => normalizeNewsItem({ ...item, provider:'FreeNews' })).filter(Boolean); if (!rows.length) throw new Error('资讯索引暂无可用文章。'); }
            catch (primaryError) { try { source = 'GDELT'; const url = 'https://api.gdeltproject.org/api/v2/doc/doc?query=' + encodeURIComponent('world OR technology OR culture') + '&mode=artlist&format=json&maxrecords=18&timespan=1d&sort=datedesc'; const payload = await fetchNewsJson(url); rows = safeList(payload.articles).map(normalizeNewsItem).filter(Boolean); if (!rows.length) throw new Error('聚合源暂无可用文章。'); }
                catch (_) { source = 'Hacker News'; const ids = await fetchNewsJson('https://hacker-news.firebaseio.com/v0/topstories.json'); const items = await Promise.all(safeList(ids).slice(0,12).map(async id => { try { return await fetchNewsJson(`https://hacker-news.firebaseio.com/v0/item/${encodeURIComponent(id)}.json`); } catch (_) { return null; } })); rows = items.filter(item => item && item.type === 'story' && item.title).map(item => normalizeNewsItem({ title:item.title, url:item.url || `https://news.ycombinator.com/item?id=${item.id}`, source:'Hacker News', text:item.text || '', publishedAt:new Date(Number(item.time || 0) * 1000).toISOString(), provider:'Hacker News' })).filter(Boolean); if (!rows.length) throw primaryError; } }
            mutate(next => { const previous = new Map(next.newsItems.map(item => [item.id,item])); rows.forEach(item => { const old = previous.get(item.id); previous.set(item.id,{ ...old,...item, content:item.content || old?.content || '', translatedTitle:old?.translatedTitle || '', translatedDescription:old?.translatedDescription || '', translatedContent:old?.translatedContent || '' }); }); next.newsItems = [...previous.values()].sort((a,b) => b.publishedAt - a.publishedAt).slice(0,80); next.newsFetchedAt = now(); });
            outcome = `已载入 ${rows.length} 条真实资讯 · ${source}。`;
        } catch (error) { outcome = `${error.message || '资讯获取失败。'}${world.newsItems.length ? ' 已保留上次内容。' : ''}`; }
        finally { newsBusy = false; render(); showToast(outcome); }
    }
    async function translateEnglish(text) { const source = String(text || '').trim(); if (!source) return ''; if (!/[A-Za-z]{3}/.test(source)) throw new Error('当前内容不是英文，无需翻译。'); const chunks = []; let chunk = '', bytes = 0; for (const character of source) { const point = character.codePointAt(0); const size = point <= 0x7f ? 1 : point <= 0x7ff ? 2 : point <= 0xffff ? 3 : 4; if (bytes + size > 450) { chunks.push(chunk); chunk = ''; bytes = 0; } chunk += character; bytes += size; } if (chunk) chunks.push(chunk); if (chunks.length > 12) throw new Error('内容过长，请查看原文。'); const result = []; for (const part of chunks) { const payload = await fetchNewsJson(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(part)}&langpair=en%7Czh-CN`); const translated = String(payload.responseData?.translatedText || '').trim(); if (Number(payload.responseStatus) !== 200 || !translated || translated === part) throw new Error('翻译服务暂不可用。'); result.push(translated); } return result.join(''); }
    async function translateCurrentPost() { const post = loadState().posts.find(item => item.id === activePostId); if (!post) return; postActionSheetOpen = false; if (showPostTranslation) { showPostTranslation = false; render(); return; } if (post.translatedTitle) { showPostTranslation = true; render(); return; } render(); try { showToast('正在翻译帖子…'); const title = await translateEnglish(post.title), body = post.body ? await translateEnglish(post.body.slice(0,2100)) + (post.body.length > 2100 ? '\n（其余内容请查看原文）' : '') : ''; mutate(next => { const target = next.posts.find(item => item.id === post.id); if (target) { target.translatedTitle = title; target.translatedBody = body; } }); showPostTranslation = true; render(); } catch (error) { showToast(error.message || '翻译失败。'); } }
    async function translateNews(id) { const item = loadState().newsItems.find(row => row.id === id); if (!item || translatingNewsId) return; if (translatedNewsVisible.has(id)) { translatedNewsVisible.delete(id); render(); return; } if (item.translatedTitle && (!item.content || item.translatedContent)) { translatedNewsVisible.add(id); render(); return; } translatingNewsId = id; render(); let failure = ''; try { const title = item.translatedTitle || await translateEnglish(item.title); const description = item.description && !item.translatedDescription ? await translateEnglish(item.description) : item.translatedDescription || ''; const content = item.content && !item.translatedContent ? await translateEnglish(item.content) : item.translatedContent || ''; mutate(next => { const target = next.newsItems.find(row => row.id === id); if (target) Object.assign(target,{ translatedTitle:title, translatedDescription:description, translatedContent:content }); }); translatedNewsVisible.add(id); } catch (error) { failure = error.message || '翻译失败，已保留英文原文。'; } finally { translatingNewsId = ''; render(); if (failure) showToast(failure); } }
    function newsTranslationButton(item) { return `<button type="button" onclick="LivingWorld.translateNews('${escapeAttr(item.id)}')" ${translatingNewsId === item.id ? 'disabled' : ''}><i class="ri-translate-2"></i> ${translatingNewsId === item.id ? '翻译中…' : translatedNewsVisible.has(item.id) ? '显示原文' : '译成中文'}</button>`; }
    function renderNewsCard(item) { const comments = loadState().newsComments.filter(row => row.newsId === item.id).length, translated = translatedNewsVisible.has(item.id); return `<article class="lw-news-card"><div class="lw-news-source"><i class="ri-global-line"></i><b>${escapeHtml(item.source)}</b><span>${timeAgo(item.publishedAt)} · ${escapeHtml(item.provider)}</span></div><button type="button" class="lw-news-open" onclick="LivingWorld.openNews('${escapeAttr(item.id)}')"><h2>${escapeHtml(translated && item.translatedTitle || item.title)}</h2>${item.description ? `<p>${escapeHtml(translated && item.translatedDescription || item.description)}</p>` : ''}${item.imageUrl ? `<img src="${escapeAttr(item.imageUrl)}" alt="" loading="lazy" onerror="this.hidden=true">` : ''}</button><div class="lw-news-actions"><button type="button" onclick="LivingWorld.openNews('${escapeAttr(item.id)}')"><i class="ri-chat-3-line"></i> ${comments} 条讨论</button>${newsTranslationButton(item)}<button type="button" onclick="LivingWorld.shareNews('${escapeAttr(item.id)}')"><i class="ri-share-forward-line"></i> 转发</button></div></article>`; }
    function renderMedia() { const world = loadState(); return `<section class="lw-media-page"><div class="lw-media-intro"><h1>现实热点</h1><button type="button" onclick="LivingWorld.fetchRealNews(true)" ${newsBusy ? 'disabled' : ''}><i class="ri-refresh-line"></i> ${newsBusy ? '获取中…' : '刷新资讯'}</button></div>${world.newsFetchedAt ? `<small class="lw-news-updated">上次获取：${new Date(world.newsFetchedAt).toLocaleString('zh-CN')}</small>` : ''}<div class="lw-news-feed">${world.newsItems.map(renderNewsCard).join('') || `<div class="lw-empty"><i class="ri-newspaper-line"></i><h2>${newsBusy ? '正在获取真实资讯' : '还没有资讯'}</h2><p>${newsBusy ? '请稍候。' : '点击刷新资讯；若来源不可用，会明确显示失败。'}</p></div>`}</div></section>`; }
    function renderNewsDetail() { const item = loadState().newsItems.find(row => row.id === activeNewsId); if (!item) return '<div class="lw-empty">这条资讯已不在本地缓存中。</div>'; const comments = loadState().newsComments.filter(row => row.newsId === item.id).sort((a,b) => a.createdAt - b.createdAt), translated = translatedNewsVisible.has(item.id); const content = translated && item.translatedContent || item.content || (translated && item.translatedDescription || item.description); return `<section class="lw-news-detail"><div class="lw-news-source"><i class="ri-global-line"></i><b>${escapeHtml(item.source)}</b><span>${timeAgo(item.publishedAt)}</span></div><h1>${escapeHtml(translated && item.translatedTitle || item.title)}</h1>${item.imageUrl ? `<img class="lw-news-hero" src="${escapeAttr(item.imageUrl)}" alt="" onerror="this.hidden=true">` : ''}<div class="lw-news-article"><strong>${item.content ? '新闻摘录' : '来源摘要'}</strong>${content ? `<p>${escapeHtml(content)}</p>` : `<p class="lw-news-unavailable">${articleLoadingId === item.id ? '正在获取正文…' : '暂时无法获取新闻正文，请查看来源原文。'}</p>`}${!item.content && articleLoadingId === item.id && content ? '<p class="lw-news-unavailable">正在获取正文…</p>' : ''}<small>内容来自 ${escapeHtml(item.source)}，版权归原发布方所有。</small></div><div class="lw-news-actions">${newsTranslationButton(item)}<a href="${escapeAttr(item.url)}" target="_blank" rel="noopener noreferrer">查看原文 <i class="ri-external-link-line"></i></a><button type="button" onclick="LivingWorld.shareNews('${escapeAttr(item.id)}')"><i class="ri-share-forward-line"></i> 转发</button></div><h2>BYND 讨论 · ${comments.length}</h2><div class="lw-news-comments">${comments.map(row => `<article class="lw-news-comment">${avatarMarkup(account(row.authorId))}<div><b>${escapeHtml(account(row.authorId).name)} <small>${timeAgo(row.createdAt)}</small></b><p>${escapeHtml(row.body)}</p></div></article>`).join('') || '<p class="lw-news-empty">还没有人讨论这条新闻。</p>'}</div><form class="lw-news-composer" onsubmit="return LivingWorld.commentNews(event)"><input id="lw-news-comment" required maxlength="1200" value="${escapeAttr(newsDraft)}" placeholder="在 BYND 留言" aria-label="新闻留言" oninput="LivingWorld.updateNewsDraft(this.value)"><button type="submit" ${newsDraft.trim() ? '' : 'disabled'} aria-label="发送留言"><i class="ri-send-plane-2-fill"></i></button></form></section>`; }
    function updateNewsDraft(value) { newsDraft = String(value || '').slice(0,1200); const button = document.querySelector('.lw-news-composer button[type=submit]'); if (button) button.disabled = !newsDraft.trim(); }
    async function fetchReaderArticle(sourceUrl) {
        const url = safeExternalUrl(sourceUrl);
        if (!url || /^(?:localhost|127(?:\.\d+){3}|10(?:\.\d+){3}|192\.168(?:\.\d+){2}|172\.(?:1[6-9]|2\d|3[01])(?:\.\d+){2}|\[?::1\]?)$/i.test(new URL(url).hostname)) throw new Error('新闻来源链接无效。');
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), 20000);
        try {
            const response = await fetch(`https://r.jina.ai/${url}`, { signal:controller.signal, headers:{ Accept:'application/json' } });
            if (!response.ok) throw new Error(`正文提取服务暂不可用（HTTP ${response.status}）。`);
            const payload = await response.json();
            const content = plainNewsText(payload.data?.content || payload.content || '').slice(0,1800);
            if (!content) throw new Error('来源没有提供可提取的正文。');
            return content;
        } finally { clearTimeout(timer); }
    }
    async function fetchArticleContent(id) {
        const item = loadState().newsItems.find(row => row.id === id);
        if (!item || item.content || articleLoadingId) return;
        articleLoadingId = id;
        if (activeNewsId === id) render();
        let failure = '';
        try {
            let content = '';
            if (item.provider === 'FreeNews') {
                try { const payload = await fetchNewsJson(`https://freenewsapi.ai/v1/article?url=${encodeURIComponent(item.url)}`); content = plainNewsText(payload.text || payload.article?.text).slice(0,1800); } catch (_) { /* Try the source itself below. */ }
            }
            if (!content) content = await fetchReaderArticle(item.url);
            mutate(next => { const target = next.newsItems.find(row => row.id === id); if (target) target.content = content; });
        } catch (error) { failure = error.message || '新闻正文暂不可用。'; }
        finally { articleLoadingId = ''; if (activeNewsId === id) render(); if (failure) showToast(failure); }
    }
    function openNews(id) { if (!loadState().newsItems.some(item => item.id === id)) return; activeNewsId = id; newsDraft = ''; activeTab = 'news-detail'; render(); void fetchArticleContent(id); }
    function commentNews(event) { event.preventDefault(); const body = document.getElementById('lw-news-comment')?.value.trim(); if (!body || !loadState().newsItems.some(item => item.id === activeNewsId)) return false; try { mutate(next => { const row = { id:uid('newscomment'), newsId:activeNewsId, authorId:next.viewerId, body:body.slice(0,1200), createdAt:now() }; next.newsComments.push(row); recordForumAction(next,'forum_news_reply',next.viewerId,activeNewsId,{ commentId:row.id, excerpt:row.body.slice(0,140) },'medium'); }); newsDraft = ''; render(); showToast('留言已发布在 BYND。'); } catch (error) { showToast(error.message); } return false; }
