'use strict';

// Ordered classic scripts. The order is part of the runtime contract: these files
// share the browser's global lexical environment and inline HTML handlers.
const scriptParts = [
    'ui/components/device.js',
    'core/navigation/router.js',
    'core/api/mcp.js',
    'apps/manual/manual.js',
    'systems/proactive-notifications/notifications.js',
    'apps/music/music.js',
    'apps/money/money.js',
    'apps/dream/dream.js',
    'apps/monitor/monitor.js',
    'apps/outing/outing.js',
    'apps/games/hub-wolfcha.js',
    'apps/games/acting.js',
    'apps/games/sync-cardmatch.js',
    'apps/games/cat-pot.js',
    'apps/games/twenty-forty-eight.js',
    'apps/games/jump.js',
    'apps/games/water-sort.js',
    'apps/games/board-games.js',
    'ui/components/folders.js',
    'apps/coreading/library.js',
    'apps/coreading/sources.js',
    'apps/coreading/shelf.js',
    'apps/coreading/thoughts.js',
    'apps/coreading/toc-stats.js',
    'apps/coreading/reviews.js',
    'apps/coreading/reader.js',
    'apps/coreading/discovery.js',
    'apps/album/album.js',
    'ui/components/page-swipe.js',
    'ui/components/desktop-layout.js',
    'ui/components/desktop-dock.js',
    'ui/components/desktop-status.js',
    'ui/components/desktop-lovely.js',
    'ui/components/desktop-widgets.js',
    'ui/components/desktop-edit.js',
    'ui/components/desktop-migrations.js'
];

const wechatParts = [
    'core/character/avatars.js',
    'apps/wechat/ui/bubble-presets.js',
    'apps/wechat/ui/render.js',
    'apps/wechat/chat/message-core.js',
    'apps/music/wechat-music.js',
    'apps/wechat/chat/composer.js',
    'apps/wechat/contacts/group-directives.js',
    'apps/wechat/chat/media-directives.js',
    'apps/wechat/chat/reply-parser.js',
    'apps/wechat/moments/reply-actions.js',
    'apps/wechat/ui/message-cards.js',
    'apps/wechat/ui/message-render.js',
    'apps/wechat/ui/bubble-menu.js',
    'core/events/script-activation.js',
    'apps/wechat/chat/send.js',
    'apps/wechat/chat/reply.js',
    'core/api/ai-reply.js',
    'apps/wechat/chat/streaming.js',
    'apps/wechat/ui/toolbar.js',
    'apps/wechat/chat/calls.js',
    'core/character/card-parser.js',
    'apps/wechat/character/import.js',
    'apps/wechat/character/delete.js',
    'core/storage/characters.js',
    'apps/wechat/contacts/news-reader.js',
    'apps/wechat/contacts/tabs.js',
    'apps/wechat/moments/favorites.js',
    'apps/wechat/chat/sticker-store.js',
    'apps/wechat/ui/me-settings.js',
    'apps/wechat/moments/moments.js',
    'apps/wechat/moments/channels.js',
    'apps/wechat/moments/live.js',
    'apps/wechat/shop/shop.js',
    'core/api/novelai.js',
    'core/api/image-generation.js',
    'apps/wechat/shop/checkout.js',
    'apps/wechat/shop/takeout.js',
    'apps/wechat/ui/chat-settings.js',
    'apps/wechat/ui/backgrounds.js',
    'apps/wechat/character/avatars.js',
    'apps/wechat/chat/image-send.js',
    'apps/wechat/chat/simulated-messages.js',
    'apps/char-phone/catalog.js',
    'apps/char-phone/brand-screens.js',
    'apps/char-phone/native-apps.js',
    'apps/char-phone/system-apps.js',
    'apps/char-phone/snapshot-data.js',
    'apps/char-phone/sync.js',
    'apps/char-phone/home.js',
    'apps/char-phone/mini-chat.js',
    'apps/char-phone/contacts.js',
    'apps/char-phone/screens.js',
    'apps/char-phone/reactions.js',
    'systems/memory/wechat-memory.js',
    'apps/wechat/chat/stickers.js'
];

// CSS files are imported in this exact order because later rules intentionally
// override earlier rules across feature boxes.
const styleParts = [
    'ui/theme/foundation.css',
    'ui/animations/tap-effects.css',
    'ui/theme/foundation-layout.css',
    'ui/components/status-bar.css',
    'ui/components/lock-screen.css',
    'ui/components/desktop.css',
    'ui/components/windows.css',
    'apps/music/music.css',
    'apps/settings/beauty.css',
    'apps/wechat/ui/wechat.css',
    'apps/wechat/ui/chat-settings.css',
    'ui/theme/dark.css',
    'core/worldbook/worldbook.css',
    'apps/wechat/chat/regex.css',
    'apps/wechat/ui/chat-view.css',
    'apps/settings/settings.css',
    'apps/settings/fonts.css',
    'apps/games/games.css',
    'apps/wechat/chat/toolbar.css',
    'core/worldbook/bookshelf.css',
    'apps/settings/polish.css',
    'ui/theme/adaptive.css',
    'ui/theme/legacy-additions.css',
    'apps/games/chicken.css',
    'apps/games/game-polish.css',
    'apps/games/wolfcha.css',
    'ui/theme/cards.css',
    'apps/wechat/ui/group-chat.css',
    'apps/games/board-games.css',
    'apps/games/acting.css',
    'apps/wechat/chat/tools.css',
    'apps/char-phone/phone.css',
    'apps/char-phone/music.css',
    'apps/outing/outing.css',
    'apps/coreading/coreading.css',
    'apps/music/netease.css',
    'apps/coreading/shelf.css',
    'ui/components/desktop-widgets.css',
    'apps/monitor/monitor.css',
    'apps/music/player-polish.css',
    'apps/monitor/pet-gallery.css',
    'apps/music/player-fixes.css',
    'apps/wechat/ui/ios-safe-area.css',
    'apps/manual/manual.css',
    'apps/coreading/shelf-tools.css',
    'core/api/mcp.css'
];

// These two apps intentionally keep their private IIFE scope. Their feature
// fragments are concatenated byte-for-byte into one runtime script.
const forumParts = [
    'systems/living-world/state.part.js',
    'apps/forum/feed/feed.part.js',
    'apps/forum/ui/render.part.js',
    'apps/forum/perspective/relationships.part.js',
    'systems/reality/news.part.js',
    'apps/forum/ui/navigation.part.js',
    'apps/forum/comments/direct-messages.part.js',
    'apps/forum/post/actions.part.js',
    'apps/forum/perspective/composer.part.js',
    'apps/forum/comments/comments.part.js',
    'apps/forum/npc/profile.part.js',
    'apps/forum/npc/generation-context.part.js',
    'systems/agent-runtime/forum-agent.part.js',
    'systems/living-world/generation.part.js',
    'systems/living-world/lifecycle.part.js'
];

const settingsParts = [
    'apps/settings/bootstrap.js',
    'apps/settings/api-load.js',
    'apps/settings/api-list.js',
    'apps/settings/api-edit.js',
    'apps/settings/api-test-list.js',
    'apps/settings/api-test-modal.js',
    'apps/settings/api-test.js',
    'apps/settings/image-provider.js',
    'apps/settings/presets.js',
    'core/storage/backup.js',
    'apps/settings/fonts.js'
];

const comicParts = [
    'apps/comic/storage/storage.part.js',
    'apps/comic/storage/media.part.js',
    'apps/comic/generator/types.part.js',
    'apps/comic/generator/plan.part.js',
    'apps/comic/generator/render.part.js',
    'apps/comic/typeset/layout.part.js',
    'apps/comic/gallery/downloads.part.js',
    'apps/comic/gallery/import-export.part.js',
    'apps/comic/ui/frame.part.js',
    'apps/comic/ui/home.part.js',
    'apps/comic/ui/create.part.js',
    'apps/comic/ui/series.part.js',
    'apps/comic/ui/viewer.part.js',
    'apps/comic/ui/editor.part.js',
    'apps/comic/ui/actions.part.js',
    'apps/comic/ui/boot.part.js'
];

module.exports = { scriptParts, wechatParts, styleParts, forumParts, comicParts, settingsParts };
