function charPhoneMailLandscape() {
    return '<svg class="cp-mail-landscape" viewBox="0 0 320 200" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="cp-mail-sky" x2="0" y2="1"><stop stop-color="#c7ccca"/><stop offset="1" stop-color="#e1dfd6"/></linearGradient></defs><path fill="url(#cp-mail-sky)" d="M0 0h320v200H0z"/><path fill="#6c797b" d="M0 92q90-18 180 8t140-3v103H0z"/><path fill="#454a47" d="M0 120l62-52 40 15 51 52-67 65H0z"/><path fill="#999b90" d="M320 130l-86 12-120 58h206z"/><path fill="none" stroke="#e6e7de" stroke-width="4" d="M105 136q60-19 153-13m-154 34q54-25 128-8m-144 41q70-34 175-21"/><path fill="#b2b1a4" d="M47 87h24v17H47z"/><path fill="#565752" d="M42 87l17-13 18 13z"/><path fill="#dad7c7" d="M80 102h29v21H80z"/><path fill="#555b55" d="M75 102l19-16 20 16z"/></svg>';
}
function charPhoneMailStamp(item) {
    return `<span class="cp-postage">${item.image?`<img src="${wcEscapeAttr(item.image)}" alt="">`:charPhoneMailLandscape()}<small>POST</small></span><span class="cp-postmark" aria-hidden="true">BYND<br>MAIL</span>`;
}
function renderCharPhoneMail(snapshot,char) {
    const e=wcEscapeHtml,items=snapshot.appData?.mail?.items||[],active=window._charPhoneSections?.mail||0;
    const detail=window._charPhoneDetail;
    if(detail?.key==='mail' && items[detail.index]) {
        const item=items[detail.index];
        return `<section class="cp-native cp-mail cp-mail-stationery cp-mail-open" data-app-layout="mail"><div class="cp-correspondence-toolbar"><button onclick="closeCharPhoneItem()">‹ 信箱</button><span>${e(item.time||item.meta)}</span></div><div class="cp-scroll"><article class="cp-writing-paper"><div class="cp-paper-heading"><small>${active===1?'SENT LETTER':'RECEIVED LETTER'}</small>${charPhoneMailStamp(item)}</div><h2>${e(item.title)}</h2><div class="cp-letter-address"><span>FROM · ${e(item.author||getWechatCharDisplayName(char))}</span><span>TO · ${e(active===1?item.recipient||'收信人':getWechatCharDisplayName(char))}</span></div><div class="cp-handwritten-body">${e(item.body)}</div><footer><span>${e(item.author||'')}</span><time>${e(item.time||item.meta)}</time></footer></article>${item.image?`<div class="cp-letter-enclosure"><img src="${wcEscapeAttr(item.image)}" alt="${wcEscapeAttr(item.title)}"></div>`:''}</div></section>`;
    }
    const rows=items.filter(i=>(i.section||0)===active);
    return `<section class="cp-native cp-mail cp-mail-stationery" data-app-layout="mail"><header class="cp-correspondence-heading"><span>CORRESPONDENCE</span><h2>信箱</h2><p>${e(getWechatCharDisplayName(char))} 的来往信件</p></header><nav class="cp-correspondence-tabs" aria-label="邮箱导航"><button aria-pressed="${active===0}" onclick="setCharPhoneSection('mail',0)">收件箱 <small>${items.filter(i=>!i.section).length}</small></button><button aria-pressed="${active===1}" onclick="setCharPhoneSection('mail',1)">已发送 <small>${items.filter(i=>i.section===1).length}</small></button></nav><label class="cp-correspondence-search"><i class="ri-search-line"></i><input aria-label="搜索邮件" placeholder="寻找一封信…" oninput="filterCharPhoneSystemRows(this.value,'.cp-postcard-entry')"></label><div class="cp-scroll cp-postcard-list">${rows.map(i=>`<button class="cp-postcard-entry" onclick="openCharPhoneItem('mail',${items.indexOf(i)})" aria-label="${wcEscapeAttr(i.title)}"><div class="cp-postcard-top"><span>POSTCARD</span>${charPhoneMailStamp(i)}</div><div class="cp-postcard-address"><div><small>FROM</small><strong>${e(i.author||'发件人')}</strong><small>TO · ${e(active===1?i.recipient||'收信人':getWechatCharDisplayName(char))}</small></div><div><h3>${e(i.title)}</h3><p>${e(i.body)}</p></div></div><div class="cp-postcard-photo">${i.image?`<img src="${wcEscapeAttr(i.image)}" alt="">`:charPhoneMailLandscape()}<span>${e(i.time||i.meta)}</span></div><i class="cp-paperclip ri-attachment-line" aria-hidden="true"></i></button>`).join('')||`<div class="cp-postcard-empty cp-brand-empty"><i class="ri-mail-open-line"></i><p>${active?'还没有寄出的心事':'信箱还安静着，等一封写给你的信'}</p><small>${snapshot.syncError?'同步未完成，请返回桌面重试。':'下一次打开，也许就有新的心事。'}</small></div>`}</div><footer class="cp-correspondence-footer">${rows.length} 封${active?'寄出的信':'来信'}</footer></section>`;
}
