    function startMessage() { activeThreadId = ''; activeTab = 'chat'; render(); const main = document.querySelector('.lw-inbox'); if (!main) return; const chooser = document.createElement('div'); chooser.className = 'lw-recipient-chooser'; chooser.innerHTML = `<div class="lw-chooser-head"><b>新私信</b><button type="button" onclick="this.closest('.lw-recipient-chooser').remove()" aria-label="关闭"><i class="ri-close-line"></i></button></div><input type="search" placeholder="搜索成员" aria-label="搜索成员" oninput="LivingWorld.filterRecipients(this.value)"><div id="lw-recipient-list"></div>`; main.prepend(chooser); filterRecipients(''); chooser.querySelector('input')?.focus(); }
    function toggleCommunityForm() { const form = document.getElementById('lw-community-form'); if (form) { form.hidden = !form.hidden; if (!form.hidden) document.getElementById('lw-community-name')?.focus(); } }
    function createCommunity(event) { event.preventDefault(); const name = document.getElementById('lw-community-name')?.value.trim(); const description = document.getElementById('lw-community-description')?.value.trim(); if (!name || !description) return false; const id = uid('community'); const composing = activeTab === 'create'; try { mutate(next => { if (next.communities.some(item => item.name.toLowerCase() === name.toLowerCase())) throw new Error('这个社区名称已存在。'); next.communities.push({ id, name: name.slice(0, 40), description: description.slice(0, 160), icon: 'ri-community-line', createdAt: now(), ownerId: next.viewerId, generated: false }); next.subscriptions[next.viewerId] = [...new Set([...safeList(next.subscriptions[next.viewerId]), id])]; addEvent(next, 'forum_community_create', next.viewerId, id, { name }, 'public'); }); activeCommunity = id; if (composing) { const select = document.getElementById('lw-post-community'); if (select) { const option = document.createElement('option'); option.value = id; option.textContent = name; select.append(option); } selectComposeCommunity(id); } else { activeTab = 'home'; render(); } showToast('社区已创建。'); } catch (error) { showToast(error.message); } return false; }
    function toggleSubscribe(id) { if (!loadState().communities.some(item => item.id === id)) return; try { mutate(next => { const rows = new Set(safeList(next.subscriptions[next.viewerId])); if (rows.has(id)) rows.delete(id); else rows.add(id); next.subscriptions[next.viewerId] = [...rows]; }); render(); } catch (error) { showToast(error.message); } }
    function filterRecipients(query) { const list = document.getElementById('lw-recipient-list'); if (!list) return; const members = visibleMembers().filter(item => `${item.name} ${item.username || ''}`.toLowerCase().includes(String(query || '').toLowerCase())); list.innerHTML = members.map(item => `<button type="button" onclick="LivingWorld.openThread('${escapeAttr(item.id)}')"><img src="${escapeAttr(item.avatar || DEFAULT_AVATAR)}" onerror="this.src='${escapeAttr(DEFAULT_AVATAR)}'"><span>${escapeHtml(item.name)}</span></button>`).join('') || '<p>没有找到成员。</p>'; }
    function openThread(id) { if (!visibleMembers().some(item => item.id === id)) { showToast('无法与该成员私信。'); return; } activeThreadId = id; activeTab = 'chat'; activityTab = 'chat'; try { mutate(next => { next.messages.forEach(item => { if (item.fromId === id && item.toId === next.viewerId && !item.readAt) item.readAt = now(); }); if (next.viewerId !== 'user') { addEvent(next, 'forum_open_dm_as', 'user', next.viewerId, { peerId: id }, 'private'); recordTrace(next, next.viewerId, 'open_dm', 'medium', { peerId: id }); } }); } catch (error) { showToast(error.message); return; } render(); }
    function sendMessage(event) { event.preventDefault(); const body = document.getElementById('lw-message-input')?.value.trim(); if (!body || !activeThreadId || !visibleMembers().some(item => item.id === activeThreadId)) return false; const peerId = activeThreadId; const senderId = viewer().id; const sentId = uid('dm'); try { mutate(next => { const message = { id: sentId, fromId: senderId, toId: peerId, body: body.slice(0, 2000), createdAt: now(), readAt: 0 }; next.messages.push(message); const action = addEvent(next, 'forum_dm', senderId, peerId, { messageId: message.id }, 'private'); grantKnowledge(next, peerId, action, senderId, 'direct', 1); if (senderId !== 'user') { const trace = addEvent(next, 'forum_impersonation', 'user', senderId, { action: 'forum_dm', messageId: sentId, targetId: peerId }, 'private'); grantKnowledge(next, 'user', trace, 'user', 'direct', 1); recordTrace(next, senderId, 'forum_dm', 'high', { messageId: sentId, targetId: peerId }); } }); dmReplyStatuses.delete(peerId); render(); void requestDirectReply(peerId, senderId, sentId); } catch (error) { showToast(error.message); } return false; }
    async function requestDirectReply(peerId, senderId, sentId) {
        const peer = account(peerId);
        if (!['char', 'npc'].includes(peer.type) || replyingThreads.has(peerId)) return;
        replyingThreads.add(peerId); dmReplyStatuses.set(peerId, { peerId, senderId, sentId, busy: true }); if (activeTab === 'chat' && activeThreadId === peerId) render();
        try {
            if (typeof window.callChatApi !== 'function') throw new Error('聊天 API 尚未配置。');
            const char = peer.type === 'char' ? safeList(window.myCharacters).find(item => item.id === peer.charId || `char:${item.id}` === peerId) : null;
            const thread = loadState().messages.filter(item => (item.fromId === senderId && item.toId === peerId) || (item.fromId === peerId && item.toId === senderId)).slice(-12);
            const history = thread.map(item => `${item.fromId === peerId ? peer.name : account(senderId).name}：${item.body}`).join('\n');
            const persona = String(char?.description || char?.personality || `${peer.summary || ''}\n身份：${peer.occupation || '普通社区成员'}。表达风格：${peer.style || '自然'}`).slice(0, 1800);
            const known = getRelevantEventsForChar(char || peerId, 3);
            const result = await window.callChatApi([{ role: 'system', content: `你是论坛成员「${peer.name}」。按以下人设和可知事实回复一条私信，只输出自己发给对方的自然语言消息，不要 JSON、旁白、系统说明或代替对方说话。\n人设：${persona}\n${known}` }, { role: 'user', content: `最近私信：\n${history}\n请回复最后一条消息。` }], { background: true, backgroundPriority: -1, stream: false, temperature: .78, max_tokens: 420, usageFeature: 'forum', usageChar: char });
            if (!result?.ok) throw new Error(result?.error || '对方暂时没有回复。');
            const body = String(result.content || '').trim().slice(0, 2000);
            if (!body) throw new Error('对方返回了空回复。');
            mutate(next => {
                if (!next.messages.some(item => item.id === sentId && item.fromId === senderId && item.toId === peerId)) throw new Error('原私信已不存在。');
                if (next.messages.some(item => item.replyTo === sentId)) return;
                const message = { id: uid('dm'), fromId: peerId, toId: senderId, body, replyTo: sentId, createdAt: now(), readAt: next.viewerId === senderId && activeThreadId === peerId ? now() : 0 };
                next.messages.push(message);
                const event = addEvent(next, 'forum_dm_reply', peerId, senderId, { messageId: message.id, replyTo: sentId }, 'private');
                grantKnowledge(next, senderId === 'user' ? senderId : 'user', event, peerId, 'direct', 1);
            });
            if (dmReplyStatuses.get(peerId)?.sentId === sentId) dmReplyStatuses.delete(peerId);
        } catch (error) { if (dmReplyStatuses.get(peerId)?.sentId === sentId) dmReplyStatuses.set(peerId, { peerId, senderId, sentId, busy: false, error: error?.message || '回复失败。' }); }
        finally {
            replyingThreads.delete(peerId);
            if ((activeTab === 'chat' && activeThreadId === peerId) || (activeTab === 'notifications' && activityTab === 'chat')) render();
            const messages = loadState().messages; const index = messages.findIndex(item => item.id === sentId);
            const latest = index < 0 ? null : messages.slice(index + 1).filter(item => item.fromId === senderId && item.toId === peerId && !messages.some(reply => reply.replyTo === item.id)).at(-1);
            if (latest) void requestDirectReply(peerId, senderId, latest.id);
        }
    }
    function retryDirectReply() { const status = dmReplyStatuses.get(activeThreadId); if (!status || status.busy || !loadState().messages.some(item => item.id === status.sentId)) return; void requestDirectReply(status.peerId, status.senderId, status.sentId); }
    function markAllRead() { try { mutate(next => { safeList(next.notifications[next.viewerId]).forEach(item => { item.read = true; }); if (next.viewerId !== 'user') { addEvent(next, 'forum_notification_read_as', 'user', next.viewerId, {}, 'private'); recordTrace(next, next.viewerId, 'mark_notifications_read', 'high'); } }); render(); } catch (error) { showToast(error.message); } }
