    function postCard(post, expanded = false) {
        const author = account(post.authorId); const com = community(post.communityId); const who = viewer().id;
        if (post.deletedAt) return `<article class="lw-post lw-post-deleted" data-post-id="${escapeAttr(post.id)}"><div class="lw-post-heading">${avatarMarkup(author)}<span class="lw-post-meta"><b>${escapeHtml(com.name)}</b><span>${escapeHtml(author.name)} · ${timeAgo(post.deletedAt)}</span></span></div><h2>该贴已删</h2><p>帖子曾存在，相关回复和知情记录仍保留。</p>${expanded ? `<small>删除时间：${new Date(post.deletedAt).toLocaleString('zh-CN')}</small>` : ''}</article>`;
        const vote = myVote(post); const marked = safeList(post.bookmarkedBy).includes(who); const joined = safeList(loadState().subscriptions[who]).includes(post.communityId);
        const body = expanded ? post.body : String(post.body || '');
        return `<article class="lw-post" data-post-id="${escapeAttr(post.id)}">
            <div class="lw-post-heading"><button class="lw-post-head" type="button" onclick="LivingWorld.openCommunity('${escapeAttr(com.id)}')">${avatarMarkup(author)}<span class="lw-post-meta"><b>${escapeHtml(com.name)}</b><span>${timeAgo(post.createdAt)} · ${escapeHtml(author.name)}</span></span></button>${!joined ? `<button type="button" class="lw-post-join" onclick="LivingWorld.toggleSubscribe('${escapeAttr(com.id)}')">加入</button>` : ''}<button type="button" class="lw-post-menu" onclick="LivingWorld.togglePostMenu('${escapeAttr(post.id)}')" aria-label="帖子操作"><i class="ri-more-2-fill"></i></button></div>
            <div class="lw-post-menu-panel" id="lw-menu-${escapeAttr(post.id)}" hidden><button type="button" onclick="LivingWorld.toggleBookmark('${escapeAttr(post.id)}')">${marked ? '取消收藏' : '收藏帖子'}</button><button type="button" onclick="LivingWorld.sharePost('${escapeAttr(post.id)}')">分享帖子</button>${post.authorId === who ? `<button type="button" onclick="LivingWorld.deletePost('${escapeAttr(post.id)}')">删除帖子</button>` : `<button type="button" onclick="LivingWorld.openProfile('${escapeAttr(author.id)}')">查看作者</button>`}</div>
            <button type="button" class="lw-post-open" onclick="LivingWorld.openPost('${escapeAttr(post.id)}')">${post.ama ? '<small class="lw-ama-label">AMA · 问我任何事</small>' : ''}<h2>${escapeHtml(post.title || '')}</h2><p>${escapeHtml(body)}</p>${post.imageUrl && post.mediaType !== 'video' ? `<img class="lw-post-image" src="${escapeAttr(post.imageUrl)}" alt="帖子图片" loading="lazy">` : ''}</button>${post.imageUrl && post.mediaType === 'video' ? `<video class="lw-post-image" controls preload="metadata" src="${escapeAttr(post.imageUrl)}"></video>` : ''}${post.poll ? renderPoll(post) : ''}
            <div class="lw-post-actions"><div class="lw-vote-pill"><button class="${vote === 1 ? 'is-on' : ''}" type="button" onclick="LivingWorld.vote('${escapeAttr(post.id)}',1)" aria-label="赞同"><i class="ri-arrow-up-line"></i></button><b>${postVotes(post)}</b><span></span><button class="${vote === -1 ? 'is-on' : ''}" type="button" onclick="LivingWorld.vote('${escapeAttr(post.id)}',-1)" aria-label="反对"><i class="ri-arrow-down-line"></i></button></div><button type="button" onclick="LivingWorld.openPost('${escapeAttr(post.id)}')"><i class="ri-chat-3-line"></i>${Number(post.commentCount || 0)}</button><button class="lw-share" type="button" onclick="LivingWorld.sharePost('${escapeAttr(post.id)}')" aria-label="分享"><i class="ri-share-forward-line"></i></button></div>
        </article>`;
    }
    function renderPoll(post) { const options = safeList(post.poll?.options); const total = options.reduce((sum, item) => sum + safeList(item.voters).length, 0); const voted = options.some(item => safeList(item.voters).includes(viewer().id)); return `<div class="lw-poll"><small>${total} 人投票${voted ? ' · 已投票' : ''}</small>${options.map(item => `<button type="button" class="${safeList(item.voters).includes(viewer().id) ? 'selected' : ''}" onclick="LivingWorld.votePoll('${escapeAttr(post.id)}','${escapeAttr(item.id)}')"><span>${escapeHtml(item.text)}</span><b>${voted && total ? Math.round(safeList(item.voters).length / total * 100) + '%' : ''}</b></button>`).join('')}</div>`; }
    function render() {
        const root = getRoot(); if (!root) return; const view = viewer();
        feedObserver?.disconnect(); feedObserver = null;
        let content = '';
        if (activeTab === 'home') content = renderHome();
        else if (activeTab === 'communities') content = renderCommunities();
        else if (activeTab === 'create') content = renderCreate();
        else if (activeTab === 'chat') content = renderChat();
        else if (activeTab === 'notifications') content = renderNotifications();
        else if (activeTab === 'profile') content = renderProfile(activePostId || view.id);
        else if (activeTab === 'detail') content = renderDetail(activePostId);
        else if (activeTab === 'settings') content = renderForumSettings();
        else if (activeTab === 'relationships') content = renderRelationships();
        else if (activeTab === 'media') content = renderMedia();
        else if (activeTab === 'news-detail') content = renderNewsDetail();
        else if (activeTab === 'promotion') content = renderPromotionDetail();
        const title = activeTab === 'detail' ? '帖子' : activeTab === 'communities' ? '社区' : activeTab === 'chat' ? (activeThreadId ? account(activeThreadId).name : '聊天') : activeTab === 'notifications' ? '活动' : activeTab === 'profile' ? account(activePostId || view.id).name : activeTab === 'settings' ? '论坛设置' : activeTab === 'relationships' ? '关系图' : activeTab === 'media' ? '媒体' : activeTab === 'news-detail' ? '新闻讨论' : activeTab === 'promotion' ? '推广' : '论坛';
        const avatar = `<button class="lw-viewer-button" type="button" onclick="LivingWorld.openProfile('${escapeAttr(view.id)}')" aria-label="打开个人主页"><img class="lw-viewer-avatar" src="${escapeAttr(view.avatar || DEFAULT_AVATAR)}" onerror="this.src='${escapeAttr(DEFAULT_AVATAR)}'"></button>`;
        const header = activeTab === 'create' ? `<header class="lw-topbar lw-create-topbar"><button type="button" class="lw-close" onclick="LivingWorld.back()" aria-label="关闭"><i class="ri-close-line"></i></button><button type="button" class="lw-community-picker" onclick="LivingWorld.toggleCommunityPicker()">${escapeHtml(community(composeCommunityId || activeCommunity || loadState().communities[0]?.id).name || '选择社区')} <i class="ri-arrow-up-down-line"></i></button><span class="lw-topbar-spacer"></span><button type="submit" form="lw-create-form" class="lw-publish" id="lw-publish" disabled>发帖</button></header>`
            : activeTab === 'home' ? `<header class="lw-topbar lw-home-topbar"><button class="lw-menu-button" type="button" onclick="LivingWorld.toggleMenu()" aria-label="打开论坛菜单"><i class="ri-menu-line"></i>${unreadMessages() + unreadNotifications() ? '<span class="lw-menu-dot" aria-label="有未读消息"></span>' : ''}</button><button class="lw-search-pill" type="button" onclick="LivingWorld.toggleSearch(true)"><i class="ri-search-line"></i><span>搜索</span></button>${avatar}</header>`
            : activeTab === 'detail' ? `<header class="lw-topbar lw-detail-topbar"><button class="lw-close" type="button" onclick="LivingWorld.back()" aria-label="关闭帖子"><i class="ri-close-line"></i></button><span class="lw-topbar-spacer"></span><button class="lw-icon-button" type="button" onclick="LivingWorld.toggleCommentSort()" aria-label="切换评论排序"><i class="ri-equalizer-2-line"></i></button><button class="lw-icon-button" type="button" onclick="LivingWorld.toggleCommentSearch()" aria-label="搜索本帖评论"><i class="ri-search-line"></i></button><button class="lw-icon-button" type="button" onclick="LivingWorld.togglePostActions()" aria-label="帖子菜单"><i class="ri-more-2-fill"></i></button>${avatar}</header>`
            : `<header class="lw-topbar"><button class="lw-back" type="button" onclick="LivingWorld.back()" aria-label="返回"><i class="ri-arrow-left-line"></i></button>${activeTab === 'profile' ? `<button class="lw-profile-title" type="button" onclick="LivingWorld.togglePerspective(true)">${escapeHtml(title)} <i class="ri-arrow-down-s-line"></i></button>` : `<strong class="lw-title">${title}</strong>`}<span class="lw-topbar-spacer"></span>${activeTab === 'notifications' ? `<button class="lw-icon-button" type="button" onclick="LivingWorld.markAllRead()" aria-label="全部标为已读"><i class="ri-mail-check-line"></i></button>` : ''}${activeTab === 'chat' && !activeThreadId ? `<button class="lw-icon-button" type="button" onclick="LivingWorld.startMessage()" aria-label="新私信"><i class="ri-edit-line"></i></button>` : ''}${activeTab === 'profile' ? `<button class="lw-icon-button" type="button" onclick="LivingWorld.toggleSearch(true)" aria-label="搜索"><i class="ri-search-line"></i></button>${activePostId === view.id ? `<button class="lw-icon-button" type="button" onclick="LivingWorld.setTab('settings')" aria-label="论坛设置"><i class="ri-settings-3-line"></i></button>` : ''}` : ''}</header>`;
        const identityHint = view.id === 'user' ? '' : `<div class="lw-identity-hint">你正在使用 ${escapeHtml(view.name)} 的身份</div>`;
        root.innerHTML = `<div class="lw-shell ${activeTab === 'create' ? 'lw-compose-shell' : ''} ${['detail','news-detail','promotion'].includes(activeTab) ? 'lw-detail-shell' : ''}">${header}${activeTab === 'detail' ? (commentSearchOpen ? renderCommentSearch() : '') : (searchOpen && activeTab !== 'create' ? renderSearchBar() : '')}${identityHint}<main class="lw-main">${content}</main>${activeTab === 'create' || ['detail','news-detail','promotion'].includes(activeTab) || (activeTab === 'chat' && activeThreadId) ? '' : renderNav()}${renderPerspectiveSheet()}${renderMenu()}${renderComposeCommunityPicker()}${renderShareSheet()}${renderPostActionSheet()}${renderReplySheet()}${activeTab === 'relationships' ? renderRelationCard() : ''}<div id="lw-ama-picker" class="lw-ama-picker" hidden></div><div id="lw-toast" class="lw-toast" hidden></div></div>`;
        if (activeTab === 'relationships') { const viewport = root.querySelector('.lw-relation-viewport'); if (viewport) viewport.scrollLeft = Math.max(0,(viewport.scrollWidth - viewport.clientWidth) / 2); }
        const composer = root.querySelector('.lw-detail-composer, .lw-news-composer');
        if (composer) root.querySelector('.lw-shell')?.append(composer);
        if (activeTab === 'detail' && activePostId && !safeList(loadState().views[view.id]).includes(activePostId)) {
            try { recordView(activePostId, 'low'); } catch (error) { console.warn('论坛浏览记录保存失败', error); }
        }
        if (activeTab === 'home' && typeof IntersectionObserver !== 'undefined') {
            feedObserver = new IntersectionObserver(entries => { for (const entry of entries) { if (!entry.isIntersecting || entry.intersectionRatio < .65) continue; feedObserver?.unobserve(entry.target); const id = entry.target.dataset.postId; if (!id || safeList(loadState().views[view.id]).includes(id)) continue; try { mutate(next => { next.views[view.id] = [...safeList(next.views[view.id]),id].slice(-80); }); } catch (error) { console.warn('论坛浏览偏好保存失败',error); } } }, { root:root.querySelector('.lw-main'), threshold:.65 });
            root.querySelectorAll('.lw-feed .lw-post[data-post-id]').forEach(card => feedObserver.observe(card));
        }
    }
    function renderWorldEmpty() { return `<div class="lw-empty lw-world-empty"><i class="ri-chat-smile-2-line"></i><b>论坛正在等待第一批故事</b><p>社区、成员和帖子都会由当前 API 生成。你也可以先创建自己的社区。</p><button class="lw-empty-action" type="button" onclick="LivingWorld.generate({bootstrap:true})" ${isGenerating ? 'disabled' : ''}>${isGenerating ? '正在生成…' : '开始生成'}</button><button class="lw-text-action" type="button" onclick="LivingWorld.setTab('communities')">创建社区</button></div>`; }
    function renderFeedEmpty() { return `<div class="lw-empty lw-feed-empty"><span>${searchQuery ? '没有找到匹配的帖子' : '这个频道暂时没有新帖子'}</span>${searchQuery ? '<button class="lw-text-action" type="button" onclick="LivingWorld.clearSearch()">清除搜索</button>' : `<button class="lw-text-action" type="button" onclick="LivingWorld.progressWorld()" ${isGenerating ? 'disabled' : ''}>${isGenerating ? '正在推进…' : '让世界继续'}</button>`}</div>`; }
    function postMatchesSearch(post, query) { const text = `${post.deletedAt ? '该贴已删' : `${post.title || ''} ${post.body || ''}`} ${account(post.authorId).name} ${community(post.communityId).name}`.toLowerCase(); return text.includes(String(query || '').trim().toLowerCase()); }
    function promotionCandidates() { const world = loadState(); if (!world.forumSettings.promotionsEnabled) return []; const who = world.viewerId; const viewed = safeList(world.views[who]).slice(-30).map(id => world.posts.find(post => post.id === id)?.communityId).filter(Boolean); const searches = safeList(world.searches[who]).slice(0,5).map(value => String(value).toLowerCase()); return world.promotions.filter(item => !item.privateFor || item.privateFor === who).map(item => ({ item, score:safeList(item.targetCommunityIds).reduce((sum,id) => sum + viewed.filter(value => value === id).length * 3 + (safeList(world.subscriptions[who]).includes(id) ? 5 : 0) + (activeCommunity === id ? 8 : 0),0) + searches.reduce((sum,term) => sum + (term && `${item.headline} ${item.body}`.toLowerCase().includes(term) ? 4 : 0),0) })).sort((a,b) => b.score - a.score || b.item.createdAt - a.item.createdAt).map(row => row.item); }
    function renderPromotion(item) { return `<article class="lw-promotion" data-promotion-id="${escapeAttr(item.id)}"><div class="lw-promotion-label"><i class="ri-megaphone-line"></i> 推广 / Sponsored ${item.privateFor ? '· 仅你可见' : ''}</div><p class="lw-promotion-sponsor">${escapeHtml(item.sponsor)}</p><h2>${escapeHtml(item.headline)}</h2><p>${escapeHtml(item.body)}</p><button type="button" onclick="LivingWorld.openPromotion('${escapeAttr(item.id)}')">${escapeHtml(item.cta || '了解详情')} <i class="ri-arrow-right-line"></i></button></article>`; }
    function renderPromotionDetail() { const item = loadState().promotions.find(row => row.id === activePostId && (!row.privateFor || row.privateFor === viewer().id)); if (!item) return '<div class="lw-empty">这条推广不在你的可见范围内。</div>'; const destination = safeList(item.targetCommunityIds).find(id => loadState().communities.some(row => row.id === id)); return `<section class="lw-promotion-detail"><div class="lw-promotion-label">推广 / Sponsored ${item.privateFor ? '· 仅你可见' : ''}</div><p class="lw-promotion-sponsor">${escapeHtml(item.sponsor)}</p><h1>${escapeHtml(item.headline)}</h1><p>${escapeHtml(item.body)}</p><div>${escapeHtml(item.detail)}</div>${destination ? `<button type="button" onclick="LivingWorld.openCommunity('${escapeAttr(destination)}')">浏览 ${escapeHtml(community(destination).name)} <i class="ri-arrow-right-line"></i></button>` : ''}</section>`; }
    function openPromotion(id) { const item = loadState().promotions.find(row => row.id === id && (!row.privateFor || row.privateFor === viewer().id)); if (!item) return; try { mutate(next => { recordForumAction(next,'forum_promotion_open',next.viewerId,id,{ sponsor:item.sponsor },'low','private'); }); activePostId = id; activeTab = 'promotion'; render(); } catch (error) { showToast(error.message); } }
    function renderFeedWithPromotions(rows) { const ads = searchQuery ? [] : promotionCandidates(); if (!ads.length) return rows.map(post => postCard(post)).join(''); const settings = loadState().forumSettings; const min = Math.max(4, Math.min(30, Number(settings.promotionMinGap || 8))); const max = Math.max(min, Math.min(30, Number(settings.promotionMaxGap || 15))); const seed = `${viewer().id}:${Math.floor(now() / DAY)}:${rows[0]?.id || ''}`.split('').reduce((sum,char) => sum + char.charCodeAt(0),0); let nextGap = min + seed % (max - min + 1); let count = 0; let adIndex = 0; return rows.map(post => { count++; let markup = postCard(post); if (count >= nextGap) { markup += renderPromotion(ads[adIndex % ads.length]); adIndex++; count = 0; nextGap = min + (seed + adIndex * 7) % (max - min + 1); } return markup; }).join(''); }
    function renderHome() { const communities = loadState().communities; const rows = searchQuery ? feed().filter(post => postMatchesSearch(post, searchQuery)) : feed(); return communities.length ? `<nav class="lw-filter-row" aria-label="帖子分类"><button class="lw-category-tab ${!activeCommunity ? 'active' : ''}" onclick="LivingWorld.setCommunity('')">推荐</button>${communities.map(item => `<button class="lw-category-tab ${activeCommunity === item.id ? 'active' : ''}" onclick="LivingWorld.setCommunity('${escapeAttr(item.id)}')">${escapeHtml(item.name)}</button>`).join('')}</nav><div class="lw-feed">${renderFeedWithPromotions(rows) || renderFeedEmpty()}</div>` : renderWorldEmpty(); }
    function renderCommunities() { const rows = loadState().communities; const subscribed = safeList(loadState().subscriptions[viewer().id]); return `<section class="lw-community-page"><div class="lw-inbox-title"><h1>社区</h1><button type="button" onclick="LivingWorld.toggleCommunityForm()"><i class="ri-add-line"></i> 创建</button></div><p>探索感兴趣的话题，进入社区阅读和发帖。</p><form id="lw-community-form" class="lw-community-form" onsubmit="return LivingWorld.createCommunity(event)" hidden><input id="lw-community-name" maxlength="40" required placeholder="社区名称" aria-label="社区名称"><input id="lw-community-description" maxlength="160" required placeholder="介绍这个社区" aria-label="社区介绍"><button type="submit">创建社区</button></form><div class="lw-community-list">${rows.map(item => { const count = loadState().posts.filter(post => post.communityId === item.id).length; return `<div class="lw-community-row"><button type="button" class="lw-community-enter" onclick="LivingWorld.openCommunity('${escapeAttr(item.id)}')"><i class="lw-community-icon ${escapeAttr(item.icon || 'ri-community-line')}"></i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.description)} · ${count} 帖</small></span></button><button type="button" class="lw-subscribe ${subscribed.includes(item.id) ? 'on' : ''}" onclick="LivingWorld.toggleSubscribe('${escapeAttr(item.id)}')">${subscribed.includes(item.id) ? '已加入' : '加入'}</button></div>`; }).join('') || '<div class="lw-empty">还没有社区。创建一个社区，或返回首页生成论坛故事。</div>'}</div></section>`; }
    function renderAmaComposer() { return `<section class="lw-ama-card" id="lw-ama-card" hidden><div class="lw-ama-head"><strong>AMA <i class="ri-information-line" title="限时问答，到期后从公开页面消失"></i></strong><button type="button" onclick="LivingWorld.toggleAma(false)" aria-label="关闭 AMA"><i class="ri-close-line"></i></button></div><input id="lw-ama-start-mode" type="hidden" value="now"><button class="lw-ama-choice" type="button" onclick="LivingWorld.openAmaPicker('start')" aria-label="选择开始时间"><span>开始时间</span><b id="lw-ama-start-label">立即开始</b><i class="ri-arrow-down-s-line" aria-hidden="true"></i></button><input id="lw-ama-start-at" class="lw-ama-date" type="datetime-local" aria-label="AMA 开始时间" hidden><input id="lw-ama-duration" type="hidden" value="4"><button class="lw-ama-choice" type="button" onclick="LivingWorld.openAmaPicker('duration')" aria-label="选择持续时间"><span>持续时间</span><b id="lw-ama-duration-label">4 小时</b><i class="ri-arrow-down-s-line" aria-hidden="true"></i></button><div class="lw-ama-selfie"><button type="button" onclick="document.getElementById('lw-image-file').click()"><i class="ri-camera-line"></i><i class="ri-image-line"></i></button><b>添加自拍（可选）</b><small>用照片介绍本次 AMA。结束后帖子会从公开页面消失，历史记录仍保留。</small></div></section>`; }
    function renderCreate() { const communities = loadState().communities; if (!communities.length) return renderWorldEmpty(); return `<form id="lw-create-form" class="lw-create-form" onsubmit="return LivingWorld.createPost(event)"><select id="lw-post-community" aria-label="选择社区" onchange="LivingWorld.updateCompose()">${communities.map(item => `<option value="${escapeAttr(item.id)}" ${item.id === (composeCommunityId || activeCommunity || communities[0].id) ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select><input id="lw-post-title" maxlength="120" required placeholder="标题" aria-label="标题" oninput="LivingWorld.updateCompose()">${renderAmaComposer()}<textarea id="lw-post-body" maxlength="3000" placeholder="正文文本（可选）" aria-label="正文文本" oninput="LivingWorld.updateCompose()"></textarea>${draftImage ? `<div class="lw-draft-image"><img src="${escapeAttr(draftImage)}" alt="待发布图片"><button type="button" onclick="LivingWorld.removeDraftImage()" aria-label="移除图片"><i class="ri-close-line"></i></button></div>` : ''}<div id="lw-poll-fields" class="lw-poll-fields" hidden><b>投票选项</b><input class="lw-poll-option" maxlength="80" placeholder="选项 1"><input class="lw-poll-option" maxlength="80" placeholder="选项 2"><button type="button" onclick="LivingWorld.addPollOption()">添加选项</button></div><input id="lw-post-image" type="url" maxlength="800" placeholder="图片链接" aria-label="图片或视频链接" hidden><div class="lw-compose-tools"><button type="button" onclick="LivingWorld.toggleLinkInput('image')" aria-label="添加链接"><i class="ri-link"></i></button><button type="button" onclick="document.getElementById('lw-image-file').click()" aria-label="添加图片"><i class="ri-image-line"></i></button><button type="button" onclick="LivingWorld.toggleLinkInput('video')" aria-label="添加视频"><i class="ri-video-line"></i></button><button type="button" onclick="LivingWorld.togglePoll()" aria-label="添加投票"><i class="ri-list-radio"></i></button><button type="button" id="lw-ama-button" onclick="LivingWorld.toggleAma()" aria-label="问我任何事"><strong>ama</strong></button><input id="lw-image-file" type="file" accept="image/*" hidden onchange="LivingWorld.pickImage(this)"></div></form>`; }
    function renderSearchBar() { const recent = safeList(loadState().searches[viewer().id]).slice(0, 4); return `<div class="lw-search-area"><form class="lw-searchbar" role="search" onsubmit="return LivingWorld.submitSearch(event)"><i class="ri-search-line"></i><input id="lw-search-input" value="${escapeAttr(searchQuery)}" autocomplete="off" placeholder="搜索" aria-label="搜索"><button type="button" onclick="LivingWorld.clearSearch()" aria-label="清除搜索"><i class="ri-close-line"></i></button></form>${!searchQuery && recent.length ? `<div class="lw-recent-searches">${recent.map(term => `<button type="button" data-term="${escapeAttr(term)}" onclick="LivingWorld.searchFor(this.dataset.term)">${escapeHtml(term)}</button>`).join('')}</div>` : ''}</div>`; }
    function forumMessageMarkup(body) { return String(body || '').split(/(bynd:\/\/forum\/post\/[A-Za-z0-9_.:%-]+)/g).map(part => /^bynd:\/\/forum\/post\//.test(part) ? `<button class="lw-inline-post-link" type="button" data-link="${escapeAttr(part)}" onclick="LivingWorld.openPostLink(this.dataset.link)">${escapeHtml(part)}</button>` : escapeHtml(part)).join(''); }
    function renderChat() {
        if (activeThreadId) { const peer = account(activeThreadId); const rows = messageThread(activeThreadId); const status = dmReplyStatuses.get(activeThreadId); return `<section class="lw-thread"><div class="lw-thread-person"><img class="lw-avatar" src="${escapeAttr(peer.avatar || DEFAULT_AVATAR)}" onerror="this.src='${escapeAttr(DEFAULT_AVATAR)}'"><b>${escapeHtml(peer.name)}</b><span>${escapeHtml(peer.username || '')}</span></div><div class="lw-thread-messages">${rows.map(item => `<div class="lw-message ${item.fromId === viewer().id ? 'mine' : ''}"><p>${forumMessageMarkup(item.body)}</p><time>${timeAgo(item.createdAt)}</time></div>`).join('') || '<p class="lw-thread-empty">这是你们的私信。发一条消息开始聊天。</p>'}${status ? `<div class="lw-dm-status">${status.busy ? '对方正在回复…' : `${escapeHtml(status.error || '回复暂时不可用。')} <button type="button" onclick="LivingWorld.retryDirectReply()">重试回复</button>`}</div>` : ''}</div><form class="lw-message-composer" onsubmit="return LivingWorld.sendMessage(event)"><input id="lw-message-input" maxlength="2000" required placeholder="${viewer().id === 'user' ? '输入消息' : `以 ${escapeAttr(viewer().name)} 的身份输入消息`}" aria-label="输入私信"><button type="submit" aria-label="发送私信"><i class="ri-send-plane-fill"></i></button></form></section>`; }
        const who = viewer().id; const peers = [...new Set(loadState().messages.filter(item => item.fromId === who || item.toId === who).map(item => item.fromId === who ? item.toId : item.fromId))].map(id => ({ id, latest: messageThread(id).at(-1) })).sort((a,b) => b.latest.createdAt - a.latest.createdAt);
        return `<section class="lw-inbox"><div class="lw-inbox-title"><h1>聊天</h1><button type="button" onclick="LivingWorld.startMessage()"><i class="ri-edit-line"></i> 新私信</button></div>${peers.map(row => { const person = account(row.id); const unread = loadState().messages.filter(item => item.fromId === row.id && item.toId === who && !item.readAt).length; return `<button class="lw-conversation" type="button" onclick="LivingWorld.openThread('${escapeAttr(row.id)}')"><img class="lw-avatar" src="${escapeAttr(person.avatar || DEFAULT_AVATAR)}" onerror="this.src='${escapeAttr(DEFAULT_AVATAR)}'"><span><b>${escapeHtml(person.name)} ${unread ? `<em>${unread}</em>` : ''}</b><small>${escapeHtml(row.latest.body)}</small></span><time>${timeAgo(row.latest.createdAt)}</time></button>`; }).join('') || `<div class="lw-empty"><i class="ri-chat-3-line"></i><h2>还没有私信</h2><p>与论坛里的成员开始一段私密对话。</p><button class="lw-empty-action" type="button" onclick="LivingWorld.startMessage()">新私信</button></div>`}</section>`;
    }
    function renderNotifications() { const rows = safeList(loadState().notifications[viewer().id]); return `<section class="lw-activity"><div class="lw-activity-tabs"><button class="${activityTab === 'notifications' ? 'active' : ''}" onclick="LivingWorld.setActivityTab('notifications')">通知${unreadNotifications() ? `<em>${unreadNotifications()}</em>` : ''}</button><button class="${activityTab === 'chat' ? 'active' : ''}" onclick="LivingWorld.setActivityTab('chat')">聊天${unreadMessages() ? `<em>${unreadMessages()}</em>` : ''}</button></div>${activityTab === 'chat' ? renderChat() : rows.map(item => `<button class="lw-note ${item.read ? '' : 'unread'}" type="button" onclick="LivingWorld.openNotice('${escapeAttr(item.id)}')"><i class="ri-notification-3-line"></i><span><b>${escapeHtml(item.title)}</b><small>${escapeHtml(item.detail)} · ${timeAgo(item.createdAt)}</small></span></button>`).join('') || '<div class="lw-empty"><i class="ri-notification-3-line"></i><h2>暂无通知</h2><p>有人回复或赞同你的帖子时，会显示在这里。</p></div>'}</section>`; }
    function commentVoteCount(comment) { return Object.values(comment.votes || {}).filter(value => Number(value) === 1 || Number(value) === -1).length; }
    function renderCommentTree(postId) {
        const allComments = commentsFor(postId); const comments = commentQuery ? allComments.filter(row => `${row.body} ${account(row.authorId).name}`.toLowerCase().includes(commentQuery.toLowerCase())) : allComments; const visible = new Set();
        const renderRow = (comment, depth = 0) => { if (visible.has(comment.id)) return ''; visible.add(comment.id); const author = account(comment.authorId); const children = commentQuery ? [] : comments.filter(row => row.parentCommentId === comment.id); const vote = Number(comment.votes?.[viewer().id] || 0); return `<article class="lw-detail-comment" data-comment-id="${escapeAttr(comment.id)}" style="--comment-depth:${Math.min(depth,4)}"><div class="lw-comment-head">${avatarMarkup(author)}<button type="button" onclick="LivingWorld.openProfile('${escapeAttr(author.id)}')">${escapeHtml(author.name)}</button><small>· ${timeAgo(comment.createdAt)}</small></div><p>${escapeHtml(comment.body)}</p>${comment.mediaUrl && comment.mediaType === 'image' ? `<img class="lw-comment-media" src="${escapeAttr(comment.mediaUrl)}" alt="评论图片" loading="lazy">` : ''}${comment.mediaUrl && comment.mediaType === 'video' ? `<video class="lw-comment-media" controls preload="metadata" src="${escapeAttr(comment.mediaUrl)}"></video>` : ''}${comment.mediaUrl && comment.mediaType === 'link' ? `<a class="lw-comment-link" href="${escapeAttr(comment.mediaUrl)}" target="_blank" rel="noopener noreferrer">查看链接 <i class="ri-external-link-line"></i></a>` : ''}<div class="lw-comment-actions"><button type="button" onclick="LivingWorld.replyToComment('${escapeAttr(comment.id)}')"><i class="ri-reply-line"></i> 回复</button><button type="button" class="${vote === 1 ? 'on' : ''}" onclick="LivingWorld.voteComment('${escapeAttr(comment.id)}',1)" aria-label="赞同评论"><i class="ri-arrow-up-line"></i></button><span>${commentVoteCount(comment)}</span><button type="button" class="${vote === -1 ? 'on' : ''}" onclick="LivingWorld.voteComment('${escapeAttr(comment.id)}',-1)" aria-label="反对评论"><i class="ri-arrow-down-line"></i></button></div>${children.map(child => renderRow(child,depth + 1)).join('')}</article>`; };
        const roots = comments.filter(row => commentQuery || !row.parentCommentId || !comments.some(parent => parent.id === row.parentCommentId));
        roots.sort((a,b) => commentSort === 'new' ? b.createdAt - a.createdAt : a.createdAt - b.createdAt);
        return roots.map(row => renderRow(row)).join('') || `<p class="lw-no-comments">${commentQuery ? '没有匹配的评论' : loadState().posts.find(post => post.id === postId)?.deletedAt ? '删除前没有回复。' : '成为第一个回复的人'}</p>`;
    }
    function renderDetail(postId) {
        const post = loadState().posts.find(item => item.id === postId);
        if (!post || !isVisible(post,viewer().id)) return '<div class="lw-empty">这条帖子已经不在你的可见范围内。</div>';
        const author = account(post.authorId); const place = community(post.communityId); const joined = safeList(loadState().subscriptions[viewer().id]).includes(post.communityId);
        const pending = !!(post.ama && post.amaStartsAt > now());
        const title = showPostTranslation && post.translatedTitle ? post.translatedTitle : post.title;
        const body = showPostTranslation && post.translatedBody ? post.translatedBody : post.body;
        const amaBadge = post.ama ? `<div class="lw-ama-status"><i class="ri-time-line"></i> AMA · ${pending ? `将于 ${new Date(post.amaStartsAt).toLocaleString('zh-CN')} 开始` : `进行中 · ${new Date(post.expiresAt).toLocaleString('zh-CN')} 结束后从公开页面消失`}</div>` : '';
        return `<section class="lw-detail"><article class="lw-detail-post"><div class="lw-detail-post-head">${avatarMarkup(author)}<div><button type="button" onclick="LivingWorld.openCommunity('${escapeAttr(place.id)}')">r/${escapeHtml(place.name)}</button><span><button type="button" onclick="LivingWorld.openProfile('${escapeAttr(author.id)}')">${escapeHtml(author.username || author.name)}</button> · ${timeAgo(post.createdAt)}</span></div>${!joined ? `<button class="lw-detail-join" type="button" onclick="LivingWorld.toggleSubscribe('${escapeAttr(place.id)}')">订阅</button>` : ''}</div>${post.deletedAt ? `<h1>该贴已删</h1><p class="lw-deleted-note">内容已从公开页面移除；先前留下的回复和记录仍在。</p>` : `${amaBadge}<h1>${escapeHtml(title)}</h1>${post.imageUrl && post.mediaType !== 'video' ? `<img class="lw-detail-image" src="${escapeAttr(post.imageUrl)}" alt="帖子图片" loading="lazy">` : ''}${post.imageUrl && post.mediaType === 'video' ? `<video class="lw-detail-image" controls preload="metadata" src="${escapeAttr(post.imageUrl)}"></video>` : ''}${body ? `<p class="lw-detail-body">${escapeHtml(body)}</p>` : ''}${post.poll ? renderPoll(post) : ''}<div class="lw-detail-actions"><div class="lw-vote-pill"><button class="${myVote(post) === 1 ? 'is-on' : ''}" type="button" onclick="LivingWorld.vote('${escapeAttr(post.id)}',1)" aria-label="赞同"><i class="ri-arrow-up-line"></i></button><b>${postVotes(post)}</b><span></span><button class="${myVote(post) === -1 ? 'is-on' : ''}" type="button" onclick="LivingWorld.vote('${escapeAttr(post.id)}',-1)" aria-label="反对"><i class="ri-arrow-down-line"></i></button></div><button type="button" onclick="LivingWorld.openReplyComposer()" ${pending ? 'disabled' : ''}><i class="ri-chat-3-line"></i> ${commentsFor(postId).length}</button><button type="button" onclick="LivingWorld.sharePost('${escapeAttr(post.id)}')" aria-label="分享帖子"><i class="ri-share-forward-line"></i></button></div>`}</article><div class="lw-detail-comments"><div class="lw-detail-comments-heading"><h2>${commentQuery ? `匹配 ${commentsFor(postId).filter(row => `${row.body} ${account(row.authorId).name}`.toLowerCase().includes(commentQuery.toLowerCase())).length} 条评论` : `${commentsFor(postId).length} 条评论`}</h2><button type="button" onclick="LivingWorld.toggleCommentSort()">${commentSort === 'new' ? '最新' : '最早'} <i class="ri-arrow-down-s-line"></i></button></div>${renderCommentTree(postId)}</div>${post.deletedAt || pending ? '' : `<button class="lw-detail-composer" type="button" onclick="LivingWorld.openReplyComposer()"><i class="ri-add-line"></i><span>加入对话</span></button>`}</section>`;
    }
    function renderCommentSearch() { return `<form class="lw-comment-search" role="search" onsubmit="return LivingWorld.submitCommentSearch(event)"><i class="ri-search-line"></i><input id="lw-comment-search" value="${escapeAttr(commentQuery)}" placeholder="搜索本帖评论" aria-label="搜索本帖评论"><button type="submit">搜索</button><button type="button" onclick="LivingWorld.clearCommentSearch()" aria-label="清除评论搜索"><i class="ri-close-line"></i></button></form>`; }
    function toggleCommentSearch() { commentSearchOpen = !commentSearchOpen; if (!commentSearchOpen) commentQuery = ''; render(); if (commentSearchOpen) document.getElementById('lw-comment-search')?.focus(); }
    function submitCommentSearch(event) { event.preventDefault(); commentQuery = document.getElementById('lw-comment-search')?.value.trim() || ''; render(); return false; }
    function clearCommentSearch() { commentQuery = ''; commentSearchOpen = false; render(); }
    function renderReplySheet() { if (activeTab !== 'detail' || !replyComposerOpen) return ''; const post = loadState().posts.find(item => item.id === activePostId); if (!post || post.deletedAt || !isVisible(post,viewer().id)) return ''; const parent = loadState().comments.find(item => item.id === replyTargetId && item.postId === post.id); return `<div class="lw-reply-shade" onclick="if(event.target===this)LivingWorld.closeReplyComposer()"><form class="lw-reply-sheet" onsubmit="return LivingWorld.reply(event,'${escapeAttr(post.id)}')"><div class="lw-reply-grip"></div><div class="lw-reply-context"><span>正在评论 <b>${escapeHtml(parent ? parent.body.slice(0,60) : post.title.slice(0,60))}</b></span><button type="button" onclick="LivingWorld.closeReplyComposer()" aria-label="收起评论框"><i class="ri-contract-up-down-line"></i></button></div><textarea id="lw-reply" maxlength="1600" required placeholder="加入对话" aria-label="回复帖子" oninput="LivingWorld.updateReplyDraft(this.value)">${escapeHtml(replyDraft)}</textarea>${replyDraftImage ? `<div class="lw-reply-preview"><img src="${escapeAttr(replyDraftImage)}" alt="待发送图片"><button type="button" onclick="LivingWorld.clearReplyMedia()" aria-label="移除图片"><i class="ri-close-line"></i></button></div>` : ''}${replyMediaKind && replyMediaKind !== 'image' ? `<input id="lw-reply-media-url" type="url" placeholder="${replyMediaKind === 'video' ? '视频链接（https://）' : replyMediaKind === 'gif' ? 'GIF 链接（https://）' : '链接（https://）'}" aria-label="附件链接" required>` : ''}<div class="lw-reply-tools"><button type="button" onclick="LivingWorld.setReplyMedia('link')" aria-label="添加链接"><i class="ri-link"></i></button><button type="button" onclick="document.getElementById('lw-reply-file').click()" aria-label="添加图片"><i class="ri-image-line"></i></button><button type="button" onclick="LivingWorld.setReplyMedia('gif')" aria-label="添加 GIF"><b>GIF</b></button><button type="button" onclick="LivingWorld.setReplyMedia('video')" aria-label="添加视频"><i class="ri-video-line"></i></button><input id="lw-reply-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden onchange="LivingWorld.pickReplyImage(this)"><span></span><button class="lw-reply-send" type="submit" ${replyDraft.trim() ? '' : 'disabled'} aria-label="发送回复"><i class="ri-send-plane-2-fill"></i></button></div></form></div>`; }
    function openReplyComposer(id = '') { if (id) replyTargetId = id; replyComposerOpen = true; render(); document.getElementById('lw-reply')?.focus(); }
    function closeReplyComposer() { replyComposerOpen = false; replyTargetId = ''; render(); }
    function updateReplyDraft(value) { replyDraft = String(value || '').slice(0,1600); const button = document.querySelector('.lw-reply-send'); if (button) button.disabled = !replyDraft.trim(); }
    function setReplyMedia(kind) { replyMediaKind = replyMediaKind === kind ? '' : kind; replyDraftImage = ''; render(); document.getElementById('lw-reply-media-url')?.focus(); }
    function clearReplyMedia() { replyMediaKind = ''; replyDraftImage = ''; render(); }
    function pickReplyImage(input) { const file = input?.files?.[0]; if (!file) return; if (!/^image\/(png|jpeg|webp|gif)$/i.test(file.type) || file.size > 20 * 1024 * 1024) { showToast('评论图片需小于 20 MB。'); return; } compressImageFile(file).then(dataUrl => { replyDraftImage = dataUrl; replyMediaKind = 'image'; render(); }).catch(error => showToast(error?.message || '图片读取失败。')); }
    function toggleCommentSort() { commentSort = commentSort === 'new' ? 'old' : 'new'; render(); }
    function replyToComment(id) { const comment = commentsFor(activePostId).find(row => row.id === id); if (!comment) return; openReplyComposer(id); }
    function clearReplyTarget() { replyTargetId = ''; render(); }
    function voteComment(id,direction) { if (![1,-1].includes(direction)) return; try { mutate(next => { const comment = next.comments.find(row => row.id === id); if (!comment || next.posts.find(post => post.id === comment.postId)?.deletedAt) throw new Error('评论不可投票。'); comment.votes ||= {}; const previous = Number(comment.votes[next.viewerId] || 0); if (previous === direction) delete comment.votes[next.viewerId]; else comment.votes[next.viewerId] = direction; if (direction === 1 && previous !== 1) recordForumAction(next,'forum_comment_like',next.viewerId,id,{ postId:comment.postId },'low'); }); render(); } catch (error) { showToast(error.message); } }
    function npcInteractionCount(npcId, world = loadState()) {
        const postAuthors = new Map(world.posts.map(post => [post.id, post.authorId]));
        const betweenPosts = world.comments.filter(item => (item.authorId === npcId && postAuthors.get(item.postId) === 'user') || (item.authorId === 'user' && postAuthors.get(item.postId) === npcId)).length;
        const privateMessages = world.messages.filter(item => (item.fromId === 'user' && item.toId === npcId) || (item.toId === 'user' && item.fromId === npcId)).length;
        const userVotes = world.posts.filter(post => post.authorId === npcId && (post.votes?.user === 1 || safeList(post.likedBy).includes('user'))).length;
        const follows = safeList(world.follows.user).includes(npcId) ? 1 : 0;
        return betweenPosts + privateMessages + userVotes + follows;
    }
    function canPromoteNpc(npc) { return !!(npc && npc.type === 'npc' && !npc.contactCharId && (npc.tier === 'persistent' || npcInteractionCount(npc.id) >= 4)); }
    function renderProfileCommunities(id) {
        const world = loadState();
        const rows = world.communities.map(item => ({ ...item, postCount: world.posts.filter(post => post.authorId === id && post.communityId === item.id && isVisible(post, viewer().id)).length })).filter(item => item.postCount > 0).sort((a, b) => b.postCount - a.postCount).slice(0, 4);
        if (!rows.length) return '';
        return `<section class="lw-profile-section"><div class="lw-profile-section-heading"><h2>活跃社区</h2><span>${rows.length} 个</span></div><div class="lw-profile-community-row">${rows.map(item => `<button class="lw-profile-community" type="button" onclick="LivingWorld.openCommunity('${escapeAttr(item.id)}')"><i class="${escapeAttr(item.icon || 'ri-community-line')}"></i><b>${escapeHtml(item.name)}</b><small>${item.postCount} 帖</small></button>`).join('')}</div></section>`;
    }
    function profileMetrics(id) {
        const world = loadState();
        const following = safeList(world.follows[id]).length;
        const knownFollowers = Object.values(world.follows).filter(list => safeList(list).includes(id)).length;
        const suggestedFollowers = Number(account(id).followerCount);
        const followers = Math.max(knownFollowers, Number.isSafeInteger(suggestedFollowers) && suggestedFollowers >= 0 ? suggestedFollowers : 0);
        const authored = world.posts.filter(post => post.authorId === id && isVisible(post,id));
        const replies = world.comments.filter(item => item.authorId === id).length;
        const media = authored.filter(post => post.imageUrl).length;
        return { following, followers, communities: new Set(authored.map(post => post.communityId)).size, posts: authored.length, replies, media };
    }
    function renderProfile(id) {
        const who = account(id); const mine = viewer().id === id; const npc = loadState().npcs.find(item => item.id === id); const posts = loadState().posts.filter(post => post.authorId === id && isVisible(post, viewer().id)); const metrics = profileMetrics(id);
        const contactControl = !mine && npc && viewer().id === 'user' ? (npc.contactCharId ? '<p class="lw-form-note">已成为你的联系人。</p>' : canPromoteNpc(npc) ? `<button class="lw-submit" type="button" onclick="LivingWorld.promoteNpc('${escapeAttr(npc.id)}')">添加为联系人</button>` : '<p class="lw-form-note">持续互动后，TA 会逐渐成为可添加的联系人。</p>') : '';
        // “我的” is the current-perspective feed, not a character sheet.
        // Keep role/persona copy out of it; public profiles may expose a shared summary.
        const publicSummary = loadState().profileEdits[id]?.summary || who.summary || (npc ? npc.summary || '' : '');
        const following = safeList(loadState().follows[viewer().id]).includes(id);
        const blocked = safeList(viewer().blocked).includes(id);
        const controls = mine ? `<button type="button" onclick="LivingWorld.editProfile()">编辑</button><button type="button" onclick="LivingWorld.setTab('create')">创建</button>` : blocked ? `<button type="button" onclick="LivingWorld.toggleBlock('${escapeAttr(id)}')">解除屏蔽</button>` : `<button type="button" onclick="LivingWorld.openThread('${escapeAttr(id)}')">私信</button><button type="button" onclick="LivingWorld.toggleBlock('${escapeAttr(id)}')">屏蔽</button><button type="button" class="primary" onclick="LivingWorld.toggleFollow('${escapeAttr(id)}')">${following ? '已关注' : '关注'}</button>`;
        const editForm = mine && profileEditOpen ? `<form class="lw-profile-editor" onsubmit="return LivingWorld.saveProfile(event)"><h2>编辑论坛资料</h2><label>显示名称<input id="lw-profile-name" maxlength="40" required value="${escapeAttr(who.name)}"></label><label>@ 昵称<input id="lw-profile-username" maxlength="32" required value="${escapeAttr(who.username || '@member')}" placeholder="@你的昵称"></label><label>简介<textarea id="lw-profile-summary" maxlength="220" placeholder="介绍一下自己">${escapeHtml(publicSummary)}</textarea></label><label>头像链接（可选）<input id="lw-profile-avatar-url" type="url" maxlength="800" placeholder="https://" value="${/^https?:\/\//i.test(who.avatar || '') ? escapeAttr(who.avatar) : ''}"></label><label class="lw-profile-upload">或选择本地头像<input id="lw-profile-avatar-file" type="file" accept="image/*" onchange="LivingWorld.pickProfileAvatar(this)"></label>${draftProfileAvatar ? '<small>已选择本地头像</small>' : ''}<div><button type="button" onclick="LivingWorld.editProfile(false)">取消</button><button type="submit">保存</button></div></form>` : '';
        let rows = posts;
        if (profileTab === 'media') rows = posts.filter(post => post.imageUrl);
        if (profileTab === 'saved') rows = loadState().posts.filter(post => safeList(post.bookmarkedBy).includes(id) && isVisible(post, viewer().id));
        const replies = loadState().comments.filter(item => item.authorId === id && loadState().posts.some(post => post.id === item.postId && isVisible(post, viewer().id))).slice().reverse();
        return `<section class="lw-profile-identity"><div class="lw-profile-controls">${controls}</div>${avatarMarkup(who,'lw-profile-avatar')}<h1>${escapeHtml(who.name)}</h1><p>${escapeHtml(who.username || '@member')} · ${metrics.followers} 位粉丝</p>${publicSummary ? `<p class="lw-profile-summary">${escapeHtml(publicSummary)}</p>` : ''}${id !== 'user' ? `<button class="lw-profile-ai-refresh" type="button" onclick="LivingWorld.refreshProfile('${escapeAttr(id)}')">更新公开资料</button>` : ''}${contactControl}${editForm}</section><div class="lw-profile-stats"><span><b>${metrics.posts}</b><small>发帖数量</small></span><span><b>${metrics.following}</b><small>关注</small></span><span><b>${metrics.followers}</b><small>粉丝</small></span></div><section class="lw-profile-section lw-profile-posts"><nav class="lw-profile-tabs" aria-label="主页内容">${[['posts','帖子'],['replies','评论'],['media','媒体'],['saved','收藏']].map(([key,label]) => `<button type="button" class="${profileTab === key ? 'active' : ''}" onclick="LivingWorld.setProfileTab('${key}')">${label}</button>`).join('')}</nav><div class="lw-feed lw-profile-feed">${profileTab === 'replies' ? replies.map(item => `<button class="lw-profile-reply" type="button" onclick="LivingWorld.openPost('${escapeAttr(item.postId)}')"><b>${escapeHtml(loadState().posts.find(post => post.id === item.postId)?.deletedAt ? '该贴已删' : loadState().posts.find(post => post.id === item.postId)?.title || '帖子')}</b><p>${escapeHtml(item.body)}</p><small>${timeAgo(item.createdAt)}</small></button>`).join('') || '<div class="lw-empty">还没有评论。</div>' : rows.map(post => postCard(post)).join('') || `<div class="lw-empty lw-profile-empty"><i class="ri-chat-smile-2-line"></i><h2>${profileTab === 'saved' ? '还没有收藏的帖子' : profileTab === 'media' ? '还没有媒体帖子' : profileTab === 'replies' ? '还没有评论' : mine ? '你还没有任何帖子' : '这里还没有帖子'}</h2><p>${mine ? '在社区中发帖后，内容会显示在这里。' : '等 TA 发帖后再来看看。'}</p>${mine && profileTab === 'posts' ? `<button type="button" class="lw-empty-action" onclick="LivingWorld.setTab('create')">创建帖子</button>` : ''}</div>`}</div></section>`;
    }
    function renderNav() { const items = [['home','主页','ri-home-5-line'],['create','创建','ri-add-line'],['notifications','收件箱','ri-notification-3-line'],['profile','你','ri-user-3-line']]; return `<nav class="lw-nav" aria-label="论坛导航">${items.map(([id,label,icon]) => `<button type="button" aria-label="${label}" title="${label}" class="${activeTab === id || (id === 'notifications' && activeTab === 'chat') ? 'active ' : ''}" onclick="LivingWorld.setTab('${id}')"><i class="${icon}" aria-hidden="true"></i>${id === 'notifications' && unreadMessages() + unreadNotifications() ? '<em class="lw-nav-dot"></em>' : ''}</button>`).join('')}</nav>`; }
    function renderMenu() { return menuOpen ? `<div class="lw-menu-shade" onclick="if(event.target===this)LivingWorld.toggleMenu(false)"><section class="lw-menu-panel" role="dialog" aria-label="论坛菜单"><h2>论坛</h2><button onclick="LivingWorld.menuGo('home')"><i class="ri-home-5-line"></i> 首页</button><button onclick="LivingWorld.menuGo('communities')"><i class="ri-group-line"></i> 社区</button><button onclick="LivingWorld.menuGo('media')"><i class="ri-newspaper-line"></i> 媒体与新闻</button><button onclick="LivingWorld.menuGo('relationships')"><i class="ri-node-tree"></i> 关系图</button><button onclick="LivingWorld.menuGo('settings')"><i class="ri-settings-3-line"></i> 论坛设置</button><button onclick="LivingWorld.returnToDesktop()"><i class="ri-apps-line"></i> 返回桌面</button></section></div>` : ''; }
    function renderComposeCommunityPicker() { if (!communityPickerOpen || activeTab !== 'create') return ''; const selected = document.getElementById('lw-post-community')?.value || composeCommunityId || activeCommunity; return `<div class="lw-community-sheet" onclick="if(event.target===this)LivingWorld.toggleCommunityPicker(false)"><section class="lw-community-panel" role="dialog" aria-modal="true" aria-label="选择发帖社区"><div class="lw-community-panel-head"><h2>选择社区</h2><button type="button" onclick="LivingWorld.toggleCommunityPicker(false)" aria-label="关闭"><i class="ri-close-line"></i></button></div><div class="lw-compose-community-list">${loadState().communities.map(item => `<button type="button" class="${item.id === selected ? 'selected' : ''}" onclick="LivingWorld.selectComposeCommunity('${escapeAttr(item.id)}')"><i class="${escapeAttr(item.icon || 'ri-community-line')}"></i><span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.description)}</small></span>${item.id === selected ? '<i class="ri-check-line"></i>' : ''}</button>`).join('')}</div><button type="button" class="lw-community-new" onclick="LivingWorld.showComposeCommunityForm()"><i class="ri-add-line"></i> 创建社区</button><form id="lw-compose-community-form" onsubmit="return LivingWorld.createCommunity(event)" hidden><input id="lw-community-name" maxlength="40" required placeholder="社区名称" aria-label="社区名称"><textarea id="lw-community-description" maxlength="160" required placeholder="介绍这个社区" aria-label="社区介绍"></textarea><button type="submit">创建并选择</button></form></section></div>`; }
    function postLink(id) { return `bynd://forum/post/${encodeURIComponent(id)}`; }
    function postIdFromLink(link) { const match = /^bynd:\/\/forum\/post\/([^/?#\s]+)$/i.exec(String(link || '').trim()); if (!match) return ''; try { return decodeURIComponent(match[1]); } catch (_) { return ''; } }
    function getPostPreview(link) { const id = postIdFromLink(link); if (!id) return null; const world = loadState(); const post = world.posts.find(item => item.id === id); if (!post || !isVisible(post,'user')) return null; const group = world.communities.find(item => item.id === post.communityId); const author = world.accounts[post.authorId] || world.npcs.find(item => item.id === post.authorId); return { id, link:postLink(id), community:group?.name || '社区', author:author?.name || (post.authorId === 'user' ? '你' : '社区成员'), title:post.deletedAt ? '该贴已删' : post.title, excerpt:post.deletedAt ? '原帖已由作者删除' : String(post.body || '').slice(0,130), deleted:!!post.deletedAt }; }
    function openPostLink(link) { const id = postIdFromLink(link); if (!id) { showToast('不是有效的 BYND 帖子链接。'); return; } const post = loadState().posts.find(item => item.id === id); if (!post) { showToast('当前设备没有这条帖子；论坛数据尚未跨设备同步。'); return; } if (!document.getElementById('lock-screen')?.classList.contains('unlocked') && typeof window.unlockPhone === 'function') window.unlockPhone(); if (typeof window.openApp === 'function') window.openApp('living-world'); openPost(id); }
    function sharedText() { if (!shareTarget) return ''; if (shareTarget.type === 'news') { const item = loadState().newsItems.find(row => row.id === shareTarget.id); return item ? `【真实资讯 · ${item.source}】${item.title}\n${item.url}` : ''; } const post = loadState().posts.find(row => row.id === shareTarget.id && !row.deletedAt); return post ? `【BYND 帖子 · ${community(post.communityId).name}】${post.title}${post.body ? `\n${post.body.slice(0,1300)}` : ''}\n${postLink(post.id)}` : ''; }
    function renderShareSheet() { if (!shareTarget) return ''; const chars = typeof window.getWechatGroupContacts === 'function' ? window.getWechatGroupContacts() : safeList(window.myCharacters).filter(item => item && !item.isGroupChat); const dms = [...new Set(loadState().messages.filter(item => item.fromId === viewer().id || item.toId === viewer().id).map(item => item.fromId === viewer().id ? item.toId : item.fromId))]; return `<div class="lw-share-shade" onclick="if(event.target===this)LivingWorld.closeShare()"><section class="lw-share-panel" role="dialog" aria-modal="true" aria-label="转发到聊天"><div class="lw-share-head"><h2>转发到</h2><button type="button" onclick="LivingWorld.closeShare()" aria-label="关闭"><i class="ri-close-line"></i></button></div><p>选择后会打开聊天并填入草稿，由你确认发送。</p><h3>角色聊天</h3>${safeList(chars).filter(char => char?.id).map(char => `<button class="lw-share-recipient" type="button" onclick="LivingWorld.shareToCharacterChat('${escapeAttr(char.id)}')">${avatarMarkup(account(`char:${char.id}`))}<span>${escapeHtml(char.chatConfig?.nickname || char.name || '')}</span><i class="ri-arrow-right-s-line"></i></button>`).join('') || '<small>还没有可转发的角色。</small>'}<h3>论坛私信</h3>${dms.map(id => `<button class="lw-share-recipient" type="button" onclick="LivingWorld.shareToForumDm('${escapeAttr(id)}')">${avatarMarkup(account(id))}<span>${escapeHtml(account(id).name)}</span><i class="ri-arrow-right-s-line"></i></button>`).join('') || '<small>还没有私信会话。你也可以先在收件箱发起私信。</small>'}</section></div>`; }
    function closeShare() { shareTarget = null; render(); }
    function shareNews(id) { if (!loadState().newsItems.some(item => item.id === id)) return; shareTarget = { type:'news', id }; render(); }
    function shareToForumDm(id) { const content = sharedText(); if (!content || !visibleMembers().some(item => item.id === id)) { showToast('转发目标不可用。'); return; } shareTarget = null; openThread(id); const input = document.getElementById('lw-message-input'); if (input) { input.value = content.slice(0,1900); input.focus(); showToast('内容已放入私信草稿，请确认后发送。'); } else showToast('私信输入框不可用，未发送。'); }
    function shareToCharacterChat(charId) { const content = sharedText(); const chars = typeof window.getWechatGroupContacts === 'function' ? window.getWechatGroupContacts() : window.myCharacters; if (!content || !safeList(chars).some(char => String(char?.id) === charId && !char.isGroupChat)) { showToast('角色聊天不可用。'); return; } if (typeof window.openApp !== 'function' || typeof window.openChat !== 'function') { showToast('角色聊天入口不可用，未发送。'); return; } try { window.openApp('wechat'); window.openChat(charId); const input = document.getElementById('wc-msg-input'); if (!input) throw new Error('角色聊天输入框不可用。'); const richEnabled = typeof window.isWechatRichInputEnabled === 'function' && window.isWechatRichInputEnabled(); if (richEnabled && typeof window.insertWechatRichInputText === 'function') { const existing = typeof window.getWechatMessageInputValue === 'function' ? window.getWechatMessageInputValue() : ''; window.insertWechatRichInputText(`${existing ? '\n' : ''}${content.slice(0,1900)}`); } else { input.value = `${input.value ? `${input.value}\n` : ''}${content.slice(0,1900)}`; input.dispatchEvent(new Event('input',{ bubbles:true })); input.focus(); } shareTarget = null; } catch (error) { try { window.openApp('living-world'); } catch (_) {} showToast(error.message || '转发草稿未能写入。'); } }
    function renderForumSettings() {
        const settings = loadState().forumSettings;
        const choice = (value, current) => value === current ? 'selected' : '';
        return `<section class="lw-settings">
            <h1>动态刷新</h1><p>只有在打开论坛时才检查到期任务。每次推进只让一位角色根据自己的已知经历选择行动或沉默；启用 Jev 时可能先增加一次决策调用，实际写作最多调用一次文本 API。手动模式不会自动推进。首次打开角色主页仍可能调用 API 生成资料。</p>
            <label>刷新方式<select id="lw-refresh-mode"><option value="manual" ${choice('manual',settings.refreshMode)}>手动</option><option value="interval" ${choice('interval',settings.refreshMode)}>固定间隔</option><option value="smart" ${choice('smart',settings.refreshMode)}>智能时段（随机）</option></select></label>
            <label>固定间隔<select id="lw-refresh-hours">${[3,6,12,24,48].map(hour => `<option value="${hour}" ${choice(hour,Number(settings.intervalHours))}>${hour} 小时</option>`).join('')}</select></label>
            <p>智能时段参考 08:00、12:30、03:00，每次在附近随机浮动；离线期间不会补扣多次 API。下次进入论坛时最多补一次。</p>
            <section class="lw-reaction-settings"><div class="lw-reaction-heading"><span class="lw-reaction-icon"><i class="ri-chat-smile-3-line"></i></span><div><h2>角色回复</h2><p>你在角色的帖子下留言后，由角色决定是否接话。</p></div></div><div class="lw-reaction-options" role="radiogroup" aria-label="角色回复调用方式">${[['forum','打开论坛时','只有进入论坛后才调用 AI 判断，不打断聊天。','ri-discuss-line'],['app','应用运行时自动','即使正在聊天或使用其他页面，也会在应用可见时判断。','ri-smartphone-line'],['off','关闭','不自动调用 AI；你的评论仍会正常保存。','ri-moon-line']].map(([mode,title,description,icon]) => `<label class="lw-reaction-option"><input type="radio" name="lw-reply-mode" value="${mode}" ${settings.replyMode === mode ? 'checked' : ''}><span class="lw-reaction-option-face"><i class="${icon}" aria-hidden="true"></i><span><strong>${title}</strong><small>${description}</small></span><i class="ri-check-line lw-reaction-check" aria-hidden="true"></i></span></label>`).join('')}</div><p class="lw-reaction-note">两种自动方式都会先等待 2–12 分钟；同一角色至少间隔 4 小时，全局至少间隔 10 分钟。未启用 Jev 时由文本模型判断；启用后先尝试 Jev，确需回复才由文本模型写内容。退出应用后不会后台调用，下次打开再检查。</p></section>
            <h2>角色主页</h2><label>头像与资料<select id="lw-profile-mode"><option value="economy" ${choice('economy',settings.profileMode)}>省生图：NPC 姓名头像 + AI 资料</option><option value="full" ${choice('full',settings.profileMode)}>完整：角色资料 + 生图头像</option></select></label>
            <p>完整模式只在角色主页实际更新时尝试生图。生图 API 未配置或失败时保留现有头像，并提示错误。</p>
            <section class="lw-promo-settings"><div class="lw-promo-settings-head"><span class="lw-promo-settings-icon"><i class="ri-megaphone-line"></i></span><div><h2>世界内推广</h2><p>让世界里的店铺与事件自然出现在信息流。</p></div></div><input id="lw-promotion-enabled" type="hidden" value="${settings.promotionsEnabled ? 'yes' : 'no'}"><div class="lw-promo-segment" role="group" aria-label="展示推广"><button type="button" class="${settings.promotionsEnabled ? 'active' : ''}" onclick="LivingWorld.setPromotionEnabled(true)">开启</button><button type="button" class="${!settings.promotionsEnabled ? 'active' : ''}" onclick="LivingWorld.setPromotionEnabled(false)">关闭</button></div><div class="lw-promo-preview"><span>信息流预览</span><strong>推广 · Sponsored</strong><p>与当前世界相关的内容会在这里出现</p></div><div class="lw-promo-sliders"><label for="lw-promotion-min"><span>最少间隔</span><b id="lw-promotion-min-display">${Number(settings.promotionMinGap || 8)} 条</b></label><input id="lw-promotion-min" type="range" min="4" max="30" value="${Number(settings.promotionMinGap || 8)}" oninput="LivingWorld.updatePromotionGap('min',this.value)"><label for="lw-promotion-max"><span>最多间隔</span><b id="lw-promotion-max-display">${Number(settings.promotionMaxGap || 15)} 条</b></label><input id="lw-promotion-max" type="range" min="4" max="30" value="${Number(settings.promotionMaxGap || 15)}" oninput="LivingWorld.updatePromotionGap('max',this.value)"></div><p class="lw-promo-note">每隔设定数量的帖子随机插入 1 条。始终明确标注「推广」，关闭后不再展示或生成。</p></section><h2 class="lw-hidden-title">已隐藏的帖子</h2>${safeList(loadState().hiddenPosts[viewer().id]).map(id => { const post = loadState().posts.find(row => row.id === id); return post ? `<button class="lw-hidden-post" type="button" onclick="LivingWorld.restoreHiddenPost('${escapeAttr(id)}')">${escapeHtml(post.title)} <span>恢复</span></button>` : ''; }).join('') || '<p class="lw-hidden-empty">暂无隐藏的帖子</p>'}
            <div class="lw-settings-actions"><button class="lw-settings-save" type="button" onclick="LivingWorld.saveForumSettings()">保存设置</button><button class="lw-settings-run" type="button" onclick="LivingWorld.progressWorld()" ${isGenerating ? 'disabled' : ''}>推进一位角色</button></div>
            <div class="lw-world-expand"><div><strong>扩展世界</strong><p>批量生成新社区、路人和世界线索。会比推进单个角色消耗更多文本额度。</p></div><button type="button" onclick="LivingWorld.generate()" ${isGenerating ? 'disabled' : ''}>扩展</button></div>${settings.lastAttemptAt ? `<small>上次自动尝试：${new Date(settings.lastAttemptAt).toLocaleString('zh-CN')}</small>` : ''}${settings.lastAutoFailure?.reason ? `<small class="lw-auto-failure">上次自动推进失败：${escapeHtml(settings.lastAutoFailure.reason)}（${new Date(settings.lastAutoFailure.at).toLocaleString('zh-CN')}）${settings.autoRetryAt ? `，将于 ${new Date(settings.autoRetryAt).toLocaleString('zh-CN')} 重试` : ''}</small>` : ''}
        </section>`;
    }
